### ISSUE TITLE
 error when npm start, can you provide .env file?

### ISSUE THREAD

**Issue by kunalified** [JAHID6597/freele#1]
Listen On PORT 3000
Successfully Connected MONGODB
GET / 500 2097 - 10.436 ms
Error: secret option required for sessions
    at session (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express-session\index.js:200:12)
    at Layer.handle [as handle_request] (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:275:10)
    at logger (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Kunal-PC\Desktop\freele-main\node_modules\express\lib\router\index.js:284:7

**Comment by JAHID6597** [comment]
PORT=
STRIPE_PUBLISHABLE_KEY=
STRIPE_SECRET_KEY=
MONGODB_URI=
SECRET_KEY=
DBUSERNAME=
DBPASSWORD=
DBNAME=
